-- ── CheckIn: missing columns ────────────────────────────────────────────────
ALTER TABLE "CheckIn" ADD COLUMN IF NOT EXISTS "type"     TEXT NOT NULL DEFAULT 'manual';
ALTER TABLE "CheckIn" ADD COLUMN IF NOT EXISTS "gpsLat"   DOUBLE PRECISION;
ALTER TABLE "CheckIn" ADD COLUMN IF NOT EXISTS "gpsLng"   DOUBLE PRECISION;
ALTER TABLE "CheckIn" ADD COLUMN IF NOT EXISTS "checkOut" TIMESTAMP(3);
ALTER TABLE "CheckIn" ADD COLUMN IF NOT EXISTS "duration" INTEGER;

-- ── Report: missing columns ──────────────────────────────────────────────────
ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "unitPrice"   DOUBLE PRECISION;
ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "totalValue"  DOUBLE PRECISION;
ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "priceItemId" INTEGER;
ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "photoUrls"   TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "gpsLat"      DOUBLE PRECISION;
ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "gpsLng"      DOUBLE PRECISION;
ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "verifiedBy"  TEXT;
ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "verifiedAt"  TIMESTAMP(3);
ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "flagVisa"    BOOLEAN NOT NULL DEFAULT false;

-- ── Visa: missing columns ────────────────────────────────────────────────────
ALTER TABLE "Visa" ADD COLUMN IF NOT EXISTS "autoGenerated"   BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Visa" ADD COLUMN IF NOT EXISTS "sourceReportIds" INTEGER[] NOT NULL DEFAULT '{}';
ALTER TABLE "Visa" ADD COLUMN IF NOT EXISTS "pdfUrl"          TEXT;

-- ── AuditLog: create if not exists ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "AuditLog" (
    "id"         SERIAL NOT NULL,
    "tableName"  TEXT NOT NULL,
    "recordId"   INTEGER NOT NULL,
    "field"      TEXT NOT NULL,
    "oldValue"   TEXT,
    "newValue"   TEXT,
    "operatorId" TEXT NOT NULL DEFAULT 'admin',
    "action"     TEXT NOT NULL DEFAULT 'update',
    "createdAt"  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id")
);

-- ── PriceLibrary + PriceItem ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "PriceLibrary" (
    "id"          SERIAL NOT NULL,
    "name"        TEXT NOT NULL,
    "type"        TEXT NOT NULL,
    "projectCode" TEXT,
    "isActive"    BOOLEAN NOT NULL DEFAULT true,
    "createdAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PriceLibrary_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "PriceItem" (
    "id"        SERIAL NOT NULL,
    "libraryId" INTEGER NOT NULL,
    "code"      TEXT NOT NULL,
    "name"      TEXT NOT NULL,
    "unit"      TEXT NOT NULL,
    "unitPrice" DOUBLE PRECISION NOT NULL,
    "spec"      TEXT,
    "keywords"  TEXT[] NOT NULL DEFAULT '{}',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PriceItem_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "PriceItem" DROP CONSTRAINT IF EXISTS "PriceItem_libraryId_fkey";
ALTER TABLE "PriceItem" ADD CONSTRAINT "PriceItem_libraryId_fkey"
    FOREIGN KEY ("libraryId") REFERENCES "PriceLibrary"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ── MaterialLibrary + Material ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "MaterialLibrary" (
    "id"          SERIAL NOT NULL,
    "name"        TEXT NOT NULL,
    "projectCode" TEXT,
    "isActive"    BOOLEAN NOT NULL DEFAULT true,
    "createdAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "MaterialLibrary_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "Material" (
    "id"        SERIAL NOT NULL,
    "libraryId" INTEGER NOT NULL,
    "code"      TEXT NOT NULL,
    "name"      TEXT NOT NULL,
    "unit"      TEXT NOT NULL,
    "planQty"   DOUBLE PRECISION NOT NULL DEFAULT 0,
    "usedQty"   DOUBLE PRECISION NOT NULL DEFAULT 0,
    "unitCost"  DOUBLE PRECISION NOT NULL DEFAULT 0,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Material_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "Material" DROP CONSTRAINT IF EXISTS "Material_libraryId_fkey";
ALTER TABLE "Material" ADD CONSTRAINT "Material_libraryId_fkey"
    FOREIGN KEY ("libraryId") REFERENCES "MaterialLibrary"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ── BaseCost ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "BaseCost" (
    "id"        SERIAL NOT NULL,
    "year"      INTEGER NOT NULL,
    "month"     INTEGER NOT NULL,
    "type"      TEXT NOT NULL,
    "amount"    DOUBLE PRECISION NOT NULL,
    "note"      TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "BaseCost_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "BaseCost" DROP CONSTRAINT IF EXISTS "BaseCost_year_month_type_key";
ALTER TABLE "BaseCost" ADD CONSTRAINT "BaseCost_year_month_type_key" UNIQUE ("year", "month", "type");

-- ── Equipment ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "Equipment" (
    "id"            SERIAL NOT NULL,
    "name"          TEXT NOT NULL,
    "code"          TEXT,
    "projectCode"   TEXT,
    "lastCheckDate" TIMESTAMP(3),
    "nextCheckDate" TIMESTAMP(3),
    "status"        TEXT NOT NULL DEFAULT 'normal',
    "note"          TEXT,
    "createdAt"     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Equipment_pkey" PRIMARY KEY ("id")
);
