import { NextRequest } from "next/server";
import { prisma } from "@/lib/prisma";

export async function GET(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url);
    const project = searchParams.get("project");
    const type = searchParams.get("type");
    const status = searchParams.get("status");

    const where: Record<string, unknown> = {};
    if (project) where.project = project;
    if (type) where.type = type;
    if (status) where.status = status;

    const visas = await prisma.visa.findMany({
      where: Object.keys(where).length > 0 ? where : undefined,
      orderBy: { createdAt: "desc" },
    });
    return Response.json(visas);
  } catch (e) {
    console.error("[GET /api/visas]", e);
    return Response.json({ error: e instanceof Error ? e.message : "查询失败" }, { status: 500 });
  }
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const {
      title, submitter, project, projectCode,
      type = "quantity",
      serialNo, reason,
      amount, items,
      daysExtended, periodReason,
      autoGenerated, sourceReportIds,
    } = body;

    if (!title || !submitter || !project) {
      return Response.json({ error: "标题、提交人、项目均为必填" }, { status: 400 });
    }

    const visa = await prisma.visa.create({
      data: {
        title,
        submitter,
        project,
        projectCode: projectCode ?? null,
        type,
        serialNo: serialNo ?? null,
        reason: reason ?? null,
        amount: Number(amount) || 0,
        items: items ?? null,
        daysExtended: daysExtended ? Number(daysExtended) : null,
        periodReason: periodReason ?? null,
        autoGenerated: autoGenerated ?? false,
        sourceReportIds: sourceReportIds ?? [],
      },
    });
    return Response.json(visa, { status: 201 });
  } catch (e) {
    console.error("[POST /api/visas]", e);
    return Response.json(
      { error: e instanceof Error ? e.message : "创建失败", detail: String(e) },
      { status: 500 }
    );
  }
}
